add_newline = false
command_timeout = 10_000

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[git_status]
conflicted = "  "
ahead = " ğŸ‡ : ${count} "
behind = " ğŸ¢ : ${count} "
diverged = " ğŸ™ ğŸ‡ : ${ahead_count} ğŸ¢ : ${behind_count} "
untracked = " ğŸ¦… : ${count} "
stashed = " ğŸ« "
modified = " ğŸ¦„ : ${count} "
staged = " ğŸ´ : ${count} "
renamed = " ğŸ¦‹ : ${count} "
deleted = " ğŸš : ${count} "

[package]
disabled = true
